# Generated by Django 2.2.1 on 2019-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190610_1104'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detail',
            name='detail_feature_value_key',
        ),
        migrations.AlterField(
            model_name='detail',
            name='value',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
