# Generated by Django 2.2.2 on 2019-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190701_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={},
        ),
    ]
